cloud:
  aws:
    credentials:
      access-key: ivF9NZRKrDXszOcXpzIy2il4d3CmHsZi1kbvAKWe
      secret-key: AKIAW3MEBVNLM6NBO6XE
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: gympics


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

