#version: '2.28.1'
services:
  database:
    image: postgres:14-alpine
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - /home/ec2-user/postgres_datapart:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gym_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    platform: linux/amd64
    restart: always


  gym-backend:
      build:
        context: ./GymBackend
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      platform: linux/amd64
      depends_on:
        - database

  gym-frontend:
      build:
        context: ./GymFrontend
        dockerfile: Dockerfile
      ports:
        - "8000:80"
      platform: linux/amd64  
      depends_on:
        - gym-backend





