version: '1'
services:
  database-postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gym_db
    platform: linux/amd64

  gym-backend:
      build:
        context: ./gymbackend
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      platform: linux/amd64

  gym-frontend:
      build:
        context: ./gymfrontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      platform: linux/amd64  